### ISSUE TITLE
Local Storage doesn't work in Safari 5

### ISSUE THREAD

**Issue by dpaola2** [dpaola2/Tou#7]
Permission dialog never appears, so there's no opportunity for the open button to appear.

**Comment by JustinTulloss** [comment]
The FileSystem API that lets us request as much room as we want will only work in Chrome. We can fall back on LocalStorage, which doesn't need permissions, but it limits us to some arbitrary amount of data. It's currently like 5MB for most browsers, which is a ton of markdown, so I don't think it's a big deal.

**Comment by dpaola2** [comment]
Alright. I'll open a ticket to fall back onto LocalStorage.
